#!/usr/bin/env bash
#This is the original script from which "zip_all_individually" is based on.
#Just a convenience thing, really. #ActiveWorlds

for i in *.rwx; do zip "$(basename "$i .rwx").zip" "$i"; done