#!/usr/bin/env bash

HEIGHT=15
WIDTH=60
CHOICE_HEIGHT=4
BACKTITLE="Retrostation Launcher v0.1"
TITLE="Systems/Consoles"
MENU="Choose a system you'd like to play:"

OPTIONS=(1 "Nintendo 64"
         2 "GB/GBC/GBA"
         3 "-"
         4 "-")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "Opening [Nintendo 64 Launcher]"
            ./m64launch
            ;;
        2)
            echo "Opening [GB/GBC/GBA Launcher]"
            ./vbamlaunch
            ;;
esac
