#!/usr/bin/env bash

HEIGHT=15
WIDTH=60
CHOICE_HEIGHT=4
BACKTITLE="Retrostation Launcher v0.1"
TITLE="GB/GBC/GBA Games"
MENU="Choose a Game you'd like to play:"

OPTIONS=(1 "(GBC) Pokemon Yellow"
         2 "-"
         3 "-"
         4 "-")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "Opening [Pokemon Yellow]"
            ~/Games/gbc/pkmn_yellow.sh
            ;;
esac
